// EXEMPLO MUDANÇA DE RISCO
const MOCK =  

{
  id: 'CM000486',
  chegada: '',
  dataChegada: '',
  dataAgendamento: '05/09/2024',
  horarioAgendamento: '08:00',
  situacao: 'SOLICITADO',
  codEmpresa: '',
  empresa: '',
  codFuncionario: '',
  funcionario: 'CARLOS ANDRE DANTAS DE OLIVEIRA',
  dataNascimento: '04/08/1978',
  sexo: 'MASCULINO',
  rg: '52.574.498-8',
  cpf: '02627831429',
  situacaoFuncionario: 'Ativo',
  cnpj: '24.584.197/0001-11',
  unidadeTrabalho: '',
  codUnidadeTrabalho: '',
  setor: 'TÉCNICO',
  codSetor: '',
  cargo: 'MESTRE DE OBRAS',
  codCargo: '',
  idFicha: '',
  dataFicha: '',
  codTipoExame: 2,
  tipoExame: 'PERIÓDICO',
  unidade: 'RIO CLARO',
  realizados: 0,
  afazer: 0,
  riscos: [],
  exames: [],
  observacoes: '',
  preferencial: '',
  atividadesEspeciais: [ 'TRABALHO EM ALTURA (NR 35)' ],
  perfil: '',
  nomeSolicitante: 'BEATRIZ CRISTINA DE GODOY',
  emailSolicitante: 'admpolastri@caprem.com.br',
  telefoneSolicitante: '(19) 99688-1036',
  anexos: [],
  mensagem: '',
  createdAt: 1725368521713,
  updatedAt: 1725368521713
}

// // ADICIONAR
// {
//   id: 'CM000490',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '16/09/2024',
//   horarioAgendamento: '08:00',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'CAMILA PAULA DE SOUZA',
//   dataNascimento: '15/01/1984',
//   sexo: 'FEMININO',
//   rg: '349546514',
//   cpf: '32728101884',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '56.387.632/0000-04',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'ADMINISTRATIVO',
//   codSetor: '',
//   cargo: 'TECNICA ATENDIMENTO DE VENDAS',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 2,
//   tipoExame: 'PERIÓDICO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'LETICIA NOVO RISSI',
//   emailSolicitante: 'rh@ibrac.com.br',
//   telefoneSolicitante: '(19) 35228-8801',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725369539158,
//   updatedAt: 1725369539158
// }

// ADICIONAR
// {
//   id: 'CM000491',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '05/09/2024',
//   horarioAgendamento: '08:00',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'RIAN DA SILVA DE SOUZA',
//   dataNascimento: '12/07/2002',
//   sexo: 'MASCULINO',
//   rg: '57.759.775-9',
//   cpf: '46872669837',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '16.883.398/0002-72',
//   unidadeTrabalho: 'UNIDADE 2',
//   codUnidadeTrabalho: '',
//   setor: 'GHE 05 - UNIDADE 2 - LINHA 1,2,3',
//   codSetor: '',
//   cargo: 'AUXILIAR DE PRODUÇÃO',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'ALINE BORGES DA SILVA',
//   emailSolicitante: 'adm@soyamill.com.br',
//   telefoneSolicitante: '(19) 99977-1370',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725369898117,
//   updatedAt: 1725369898117
// }





// ADICIONAR
// {
//   id: 'CM000492',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '04/09/2024',
//   horarioAgendamento: '13:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'MARIA EMILIA BERGOCE ARRUDA',
//   dataNascimento: '13/11/1975',
//   sexo: 'FEMININO',
//   rg: '291749227',
//   cpf: '35367566898',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '50.106.939/0002-94',
//   unidadeTrabalho: 'RUA 3-B',
//   codUnidadeTrabalho: '',
//   setor: 'AÇOUGUE',
//   codSetor: '',
//   cargo: 'AÇOUGUEIRA',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'RENAN ZADRA',
//   emailSolicitante: 'pantoja.pantojarh@yahoo.com.br',
//   telefoneSolicitante: '',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725370387181,
//   updatedAt: 1725370387181
// }






// {
// sexo: 'FEMININO',
// rg: '678059597',
// cpf: '05720173323',
// situacaoFuncionario: 'Ativo',
// cnpj: '50.106.939/0002-94',
// unidadeTrabalho: 'RUA 3-B',
// codUnidadeTrabalho: '',
// setor: 'LOJA/AÇOUGUE',
// codSetor: '',
// cargo: 'BALCONISTA',
// codCargo: '',
// idFicha: '',
// dataFicha: '',
// codTipoExame: 1,
// tipoExame: 'ADMISSIONAL',
// unidade: 'RIO CLARO',
// realizados: 0,
// afazer: 0,
// riscos: [],
// exames: [],
// observacoes: '',
// preferencial: '',
// atividadesEspeciais: [],
// perfil: '',
// nomeSolicitante: 'RENAN ZADRA',
// emailSolicitante: 'pantoja.pantojarh@yahoo.com.br',
// telefoneSolicitante: '',
// anexos: [],
// mensagem: '',
// createdAt: 1725285866428,
// updatedAt: 1725285866428
// }


// ERRO CODIGO DO SETOR
// {
//     id: 'CM000466',
//     chegada: '',
//     dataChegada: '',
//     dataAgendamento: '04/09/2024',
//     horarioAgendamento: '08:30',
//     situacao: 'SOLICITADO',
//     codEmpresa: '',
//     empresa: '',
//     codFuncionario: '',
//     funcionario: 'THAIS TENELLI',
//     dataNascimento: '28/12/1977',
//     sexo: 'FEMININO',
//     rg: '3030007539',
//     cpf: '23122121883',
//     situacaoFuncionario: 'Ativo',
//     cnpj: '57.893.802/0001-95',
//     unidadeTrabalho: '',
//     codUnidadeTrabalho: '',
//     setor: 'LIMPEZA',
//     codSetor: '',
//     cargo: 'LIMPEZA',
//     codCargo: '',
//     idFicha: '',
//     dataFicha: '',
//     codTipoExame: 1,
//     tipoExame: 'ADMISSIONAL',
//     unidade: 'RIO CLARO',
//     realizados: 0,
//     afazer: 0,
//     riscos: [],
//     exames: [],
//     observacoes: '',
//     preferencial: '',
//     atividadesEspeciais: [],
//     perfil: '',
//     nomeSolicitante: 'JAQUELINE APARECIDA BUCIOLLI BUSO',
//     emailSolicitante: 'padaria.claret@hotmail.com',
//     telefoneSolicitante: '(19) 98943-9297',
//     anexos: [],
//     mensagem: '',
//     createdAt: 1725362032180,
//     updatedAt: 1725362032180
//   }

// {
//   id: 'CM000405',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '03/09/2024',
//   horarioAgendamento: '09:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'INOVAÇÃO RH TRABALHOS TEMPORARIOS',
//   codFuncionario: '',
//   funcionario: 'BRUNO ELI DA SILVA',
//   dataNascimento: '11/03/1997',
//   sexo: 'MASCULINO',
//   rg: '565915290',
//   cpf: '49582643889',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '01.969.452/0001-49',
//   unidadeTrabalho: 'CHEMSON',
//   codUnidadeTrabalho: '',
//   setor: 'SOLID CA/ZN',
//   codSetor: '',
//   cargo: 'AJUDANTE DE PRODUÇÃO',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: 'SEGUIR PCMSO DA CHEMSON',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'THAIS',
//   emailSolicitante: 'atendimento@inovacaose.com.br',
//   telefoneSolicitante: '(19) 99644-1281',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725285925106,
//   updatedAt: 1725285925106
// }







// NAO TEM CODIGO EMPRESA (KIT)
// {
//     id: 'CM000469',
//     chegada: '',
//     dataChegada: '',
//     dataAgendamento: '04/09/2024',
//     horarioAgendamento: '08:30',
//     situacao: 'SOLICITADO',
//     codEmpresa: '',
//     empresa: '',
//     codFuncionario: '',
//     funcionario: 'DANIELA SIMONE BUENO DA SILVA PEREIRA',
//     dataNascimento: '03/11/1976',
//     sexo: 'FEMININO',
//     rg: '279582894',
//     cpf: '19694026873',
//     situacaoFuncionario: 'Ativo',
//     cnpj: '10.413.463/0007-24',
//     unidadeTrabalho: 'CND - RIO CLARO (ESTÁDIO)',
//     codUnidadeTrabalho: '',
//     setor: 'CAIXA',
//     codSetor: '',
//     cargo: 'OPERADORA DE CAIXA',
//     codCargo: '',
//     idFicha: '',
//     dataFicha: '',
//     codTipoExame: 1,
//     tipoExame: 'ADMISSIONAL',
//     unidade: 'RIO CLARO',
//     realizados: 0,
//     afazer: 0,
//     riscos: [],
//     exames: [],
//     observacoes: '',
//     preferencial: '',
//     atividadesEspeciais: [],
//     perfil: '',
//     nomeSolicitante: 'SAMUELL VICTOR LACERDA MAGALHAES',
//     emailSolicitante: 'samuell.magalhaes@casaevida.com.br',
//     telefoneSolicitante: '',
//     anexos: [],
//     mensagem: '',
//     createdAt: 1725362958410,
//     updatedAt: 1725362958410
//   }


// // FICHA CLINICA NAO ENCONTRADA
// {
//   id: 'CM000445',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '05/09/2024',
//   horarioAgendamento: '08:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'JOSIMAR SIQUEIRA DE PAULA',
//   dataNascimento: '17/02/1990',
//   sexo: 'MASCULINO',
//   rg: '463530743',
//   cpf: '40512749850',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '07.677.731/0020-04',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'ADMINISTRATIVO',
//   codSetor: '',
//   cargo: 'ANALISTA ADMINISTRATIVO',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 2,
//   tipoExame: 'PERIÓDICO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'ANDRÉ PIRES PEREIRA',
//   emailSolicitante: 'andrepp@vix.com.br',
//   telefoneSolicitante: '(19) 99999-9999',
//   anexos: [
//     'https://www.jotform.com/uploads/cmsoatendimento/230894671029664/6011107804817322224/ASO - JOSIMAR SIQUEIRA DE PAULA.PDF',
//     'https://www.jotform.com/uploads/cmsoatendimento/230894671029664/6011107804817322224/FICHA MÉDICA 2024- JOSIMAR SIQUEIRA DE PAULA.docx'
//   ],
//   mensagem: '',
//   createdAt: 1725301842530,
//   updatedAt: 1725301842530
// }

// {
//   id: 'CM000445',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '05/09/2024',
//   horarioAgendamento: '08:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'JOSIMAR SIQUEIRA DE PAULA',
//   dataNascimento: '17/02/1990',
//   sexo: 'MASCULINO',
//   rg: '463530743',
//   cpf: '40512749850',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '07.677.731/0020-04',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'ADMINISTRATIVO',
//   codSetor: '',
//   cargo: 'ANALISTA ADMINISTRATIVO',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 2,
//   tipoExame: 'PERIÓDICO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'ANDRÉ PIRES PEREIRA',
//   emailSolicitante: 'andrepp@vix.com.br',
//   telefoneSolicitante: '(19) 99999-9999',
//   anexos: [
//     'https://www.jotform.com/uploads/cmsoatendimento/230894671029664/6011107804817322224/ASO - JOSIMAR SIQUEIRA DE PAULA.PDF',
//     'https://www.jotform.com/uploads/cmsoatendimento/230894671029664/6011107804817322224/FICHA MÉDICA 2024- JOSIMAR SIQUEIRA DE PAULA.docx'
//   ],
//   mensagem: '',
//   createdAt: 1725301585114,
//   updatedAt: 1725301585114
// }



// {
//   id: 'CM000406',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '03/09/2024',
//   horarioAgendamento: '09:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'INOVAÇÃO RH TRABALHOS TEMPORARIOS',
//   codFuncionario: '',
//   funcionario: 'BRUNO AUGUSTO AMORIM',
//   dataNascimento: '30/06/1993',
//   sexo: 'MASCULINO',
//   rg: '488335085',
//   cpf: '41616299827',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '01.969.452/0001-49',
//   unidadeTrabalho: 'CHEMSON',
//   codUnidadeTrabalho: '',
//   setor: 'SOLID CA/ZN',
//   codSetor: '',
//   cargo: 'AJUDANTE DE PRODUÇÃO',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: 'SEGUIR PCMSO DA CHEMSON',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'THAIS',
//   emailSolicitante: 'atendimento@inovacaose.com.br',
//   telefoneSolicitante: '(19) 99644-1281',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725286015936,
//   updatedAt: 1725286015936
// }








// {
//   id: 'CM000409',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '05/09/2024',
//   horarioAgendamento: '13:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'MV SERVIÇOS LTDA',
//   codFuncionario: '',
//   funcionario: 'TALITA APARECIDA CAETANO ALMEIDA',
//   dataNascimento: '18/06/1988',
//   sexo: 'FEMININO',
//   rg: '40247000X',
//   cpf: '32172961841',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '03.384.710/0001-59',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'ESCOLAR',
//   codSetor: '',
//   cargo: 'MONITORA DE ALUNOS',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 3,
//   tipoExame: 'RETORNO AO TRABALHO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: 'CBO 334110\r\nENTREGAR VIA DO ASO AO COLABORADOR',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'LEANDRO OLIVEIRA',
//   emailSolicitante: 'monitoresrioclaro@gmail.com',
//   telefoneSolicitante: '(19) 99887-8604',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725286696648,
//   updatedAt: 1725286696648
// }






// PROBLEMA SAAJ
// {
//   id: 'CM000322',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '11/09/2024',
//   horarioAgendamento: '08:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'AED MONITORAMENTO',
//   codFuncionario: '',
//   funcionario: 'HEBE ALVES GONCALVES',
//   dataNascimento: '30/07/1985',
//   sexo: 'FEMININO',
//   rg: '425712539',
//   cpf: '33340387850',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '21.533.191/0001-27',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'OPERACIONAL',
//   codSetor: '',
//   cargo: 'SUPERVISORA ADMINISTRATIVA',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 2,
//   tipoExame: 'PERIÓDICO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'WITHNEY',
//   emailSolicitante: 'withney.caroline@aedmonitoramento.com.br',
//   telefoneSolicitante: '(01) 93315-1030',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725035575936,
//   updatedAt: 1725035575936
// }


// PROBLEMA SAAJ
// {
//   id: 'CM000389',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '03/09/2024',
//   horarioAgendamento: '10:00',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'SARTORICMS',
//   codFuncionario: '',
//   funcionario: 'WILLIAN SANCHES DA SILVA',
//   dataNascimento: '18/07/1984',
//   sexo: 'MASCULINO',
//   rg: '328281529',
//   cpf: '22661939881',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '04.861.623/0001-00',
//   unidadeTrabalho: 'RIO CLARO SP',
//   codUnidadeTrabalho: '',
//   setor: '40204 - CENTRO DE TORNEAMENTO MULTIFUSO',
//   codSetor: '',
//   cargo: 'OPERADOR DE MÁQUINA CNC II C',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'SERGIO LUIS DEBONI',
//   emailSolicitante: 'sergio.deboni@sartori.ind.br',
//   telefoneSolicitante: '(19) 03538-1910',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725282702048,
//   updatedAt: 1725282702048
// }


// ERRO AXIOS
// {
//   id: 'CM000389',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '03/09/2024',
//   horarioAgendamento: '10:00',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'SARTORICMS',
//   codFuncionario: '',
//   funcionario: 'WILLIAN SANCHES DA SILVA',
//   dataNascimento: '18/07/1984',
//   sexo: 'MASCULINO',
//   rg: '328281529',
//   cpf: '22661939881',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '04.861.623/0001-00',
//   unidadeTrabalho: 'RIO CLARO SP',
//   codUnidadeTrabalho: '',
//   setor: '40204 - CENTRO DE TORNEAMENTO MULTIFUSO',
//   codSetor: '',
//   cargo: 'OPERADOR DE MÁQUINA CNC II C',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'SERGIO LUIS DEBONI',
//   emailSolicitante: 'sergio.deboni@sartori.ind.br',
//   telefoneSolicitante: '(19) 03538-1910',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725282849898,
//   updatedAt: 1725282849898
// }



 module.exports = MOCK