
const MOCK =  

// // ERRO, HIERARQUIA INATIVA
// {
//   id: 'CM000499',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '05/09/2024',
//   horarioAgendamento: '08:00',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'MEIRE AKIE FIUZA',
//   dataNascimento: '02/05/1968',
//   sexo: 'FEMININO',
//   rg: '20.937.874-8',
//   cpf: '34278730802',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '44.667.202/0002-48',
//   unidadeTrabalho: 'MATRIZ',
//   codUnidadeTrabalho: '',
//   setor: 'COZINHA',
//   codSetor: '',
//   cargo: 'COZINHEIRA III',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [ 'MANIPULAÇÃO DE ALIMENTOS (VIGILÂNCIA)' ],
//   perfil: '',
//   nomeSolicitante: 'TAMARU HORTICENTER COMERCIO DE ALIMENTOS LTDA',
//   emailSolicitante: 'rh.horticenter@gmail.com',
//   telefoneSolicitante: '(19) 99323-3633',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725372534796,
//   updatedAt: 1725372534796
// }




// CLINICA EXTERNA
// {
//   id: 'CM000507',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '13/09/2024',
//   horarioAgendamento: '08:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'ANA LAURA GOMES',
//   dataNascimento: '14/09/1978',
//   sexo: 'FEMININO',
//   rg: '299852696',
//   cpf: '25808404860',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '36.146.575/0001-64',
//   unidadeTrabalho: 'RIO CLARO',
//   codUnidadeTrabalho: '',
//   setor: 'PEDAGIO 01 RIO CLARO KM 181+500',
//   codSetor: '',
//   cargo: 'AGENTE DE PEDAGIO II',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 5,
//   tipoExame: 'DEMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: 'SOMOS CLIENTE ENGEMED',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'MIRELA',
//   emailSolicitante: 'mirela.silva@ibhservicos.com.br',
//   telefoneSolicitante: '(16) 99232-9270',
//   anexos: [
//     'https://www.jotform.com/uploads/cmsoatendimento/230894671029664/6011845824124002150/GUIA - ANA LAURA.pdf'
//   ],
//   mensagem: '',
//   createdAt: 1725375390477,
//   updatedAt: 1725375390477
// }




// ERRO CODIGO DO SETOR
// {
//     id: 'CM000466',
//     chegada: '',
//     dataChegada: '',
//     dataAgendamento: '04/09/2024',
//     horarioAgendamento: '08:30',
//     situacao: 'SOLICITADO',
//     codEmpresa: '',
//     empresa: '',
//     codFuncionario: '',
//     funcionario: 'THAIS TENELLI',
//     dataNascimento: '28/12/1977',
//     sexo: 'FEMININO',
//     rg: '3030007539',
//     cpf: '23122121883',
//     situacaoFuncionario: 'Ativo',
//     cnpj: '57.893.802/0001-95',
//     unidadeTrabalho: '',
//     codUnidadeTrabalho: '',
//     setor: 'LIMPEZA',
//     codSetor: '',
//     cargo: 'LIMPEZA',
//     codCargo: '',
//     idFicha: '',
//     dataFicha: '',
//     codTipoExame: 1,
//     tipoExame: 'ADMISSIONAL',
//     unidade: 'RIO CLARO',
//     realizados: 0,
//     afazer: 0,
//     riscos: [],
//     exames: [],
//     observacoes: '',
//     preferencial: '',
//     atividadesEspeciais: [],
//     perfil: '',
//     nomeSolicitante: 'JAQUELINE APARECIDA BUCIOLLI BUSO',
//     emailSolicitante: 'padaria.claret@hotmail.com',
//     telefoneSolicitante: '(19) 98943-9297',
//     anexos: [],
//     mensagem: '',
//     createdAt: 1725362032180,
//     updatedAt: 1725362032180
//   }








// NAO TEM CODIGO EMPRESA (KIT)
{
    id: 'CM000469',
    chegada: '',
    dataChegada: '',
    dataAgendamento: '04/09/2024',
    horarioAgendamento: '08:30',
    situacao: 'SOLICITADO',
    codEmpresa: '',
    empresa: '',
    codFuncionario: '',
    funcionario: 'DANIELA SIMONE BUENO DA SILVA PEREIRA',
    dataNascimento: '03/11/1976',
    sexo: 'FEMININO',
    rg: '279582894',
    cpf: '19694026873',
    situacaoFuncionario: 'Ativo',
    cnpj: '10.413.463/0007-24',
    unidadeTrabalho: 'CND - RIO CLARO (ESTÁDIO)',
    codUnidadeTrabalho: '',
    setor: 'CAIXA',
    codSetor: '',
    cargo: 'OPERADORA DE CAIXA',
    codCargo: '',
    idFicha: '',
    dataFicha: '',
    codTipoExame: 1,
    tipoExame: 'ADMISSIONAL',
    unidade: 'RIO CLARO',
    realizados: 0,
    afazer: 0,
    riscos: [],
    exames: [],
    observacoes: '',
    preferencial: '',
    atividadesEspeciais: [],
    perfil: '',
    nomeSolicitante: 'SAMUELL VICTOR LACERDA MAGALHAES',
    emailSolicitante: 'samuell.magalhaes@casaevida.com.br',
    telefoneSolicitante: '',
    anexos: [],
    mensagem: '',
    createdAt: 1725362958410,
    updatedAt: 1725362958410
  }


// FICHA CLINICA NAO ENCONTRADA (KIT ?? )
// {
//   id: 'CM000445',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '05/09/2024',
//   horarioAgendamento: '08:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'JOSIMAR SIQUEIRA DE PAULA',
//   dataNascimento: '17/02/1990',
//   sexo: 'MASCULINO',
//   rg: '463530743',
//   cpf: '40512749850',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '07.677.731/0020-04',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'ADMINISTRATIVO',
//   codSetor: '',
//   cargo: 'ANALISTA ADMINISTRATIVO',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 2,
//   tipoExame: 'PERIÓDICO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'ANDRÉ PIRES PEREIRA',
//   emailSolicitante: 'andrepp@vix.com.br',
//   telefoneSolicitante: '(19) 99999-9999',
//   anexos: [
//     'https://www.jotform.com/uploads/cmsoatendimento/230894671029664/6011107804817322224/ASO - JOSIMAR SIQUEIRA DE PAULA.PDF',
//     'https://www.jotform.com/uploads/cmsoatendimento/230894671029664/6011107804817322224/FICHA MÉDICA 2024- JOSIMAR SIQUEIRA DE PAULA.docx'
//   ],
//   mensagem: '',
//   createdAt: 1725301842530,
//   updatedAt: 1725301842530
// }




// CPF INAVALIDO
// {
//   id: 'CM000522',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '09/09/2024',
//   horarioAgendamento: '07:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: '',
//   codFuncionario: '',
//   funcionario: 'MOACIR JOSÉ SILVA',
//   dataNascimento: '06/11/1965',
//   sexo: 'MASCULINO',
//   rg: '19.071.129-2',
//   cpf: '26683207601',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '51.061.885/0001-70',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'TRANSPORTE',
//   codSetor: '',
//   cargo: 'MOTORISTA',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 2,
//   tipoExame: 'PERIÓDICO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'ADRIANA LEITE',
//   emailSolicitante: 'fdouradarc@gmail.com',
//   telefoneSolicitante: '(19) 99798-2345',
//   anexos: [],
//   erros: [],
//   createdAt: 1725383071883,
//   updatedAt: 1725383071883
// }






 module.exports = MOCK