// EXEMPLO MUDANÇA DE RISCO
const MOCK =  

// {
// sexo: 'FEMININO',
// rg: '678059597',
// cpf: '05720173323',
// situacaoFuncionario: 'Ativo',
// cnpj: '50.106.939/0002-94',
// unidadeTrabalho: 'RUA 3-B',
// codUnidadeTrabalho: '',
// setor: 'LOJA/AÇOUGUE',
// codSetor: '',
// cargo: 'BALCONISTA',
// codCargo: '',
// idFicha: '',
// dataFicha: '',
// codTipoExame: 1,
// tipoExame: 'ADMISSIONAL',
// unidade: 'RIO CLARO',
// realizados: 0,
// afazer: 0,
// riscos: [],
// exames: [],
// observacoes: '',
// preferencial: '',
// atividadesEspeciais: [],
// perfil: '',
// nomeSolicitante: 'RENAN ZADRA',
// emailSolicitante: 'pantoja.pantojarh@yahoo.com.br',
// telefoneSolicitante: '',
// anexos: [],
// mensagem: '',
// createdAt: 1725285866428,
// updatedAt: 1725285866428
// }



{
  id: 'CM000405',
  chegada: '',
  dataChegada: '',
  dataAgendamento: '03/09/2024',
  horarioAgendamento: '09:30',
  situacao: 'SOLICITADO',
  codEmpresa: '',
  empresa: 'INOVAÇÃO RH TRABALHOS TEMPORARIOS',
  codFuncionario: '',
  funcionario: 'BRUNO ELI DA SILVA',
  dataNascimento: '11/03/1997',
  sexo: 'MASCULINO',
  rg: '565915290',
  cpf: '49582643889',
  situacaoFuncionario: 'Ativo',
  cnpj: '01.969.452/0001-49',
  unidadeTrabalho: 'CHEMSON',
  codUnidadeTrabalho: '',
  setor: 'SOLID CA/ZN',
  codSetor: '',
  cargo: 'AJUDANTE DE PRODUÇÃO',
  codCargo: '',
  idFicha: '',
  dataFicha: '',
  codTipoExame: 1,
  tipoExame: 'ADMISSIONAL',
  unidade: 'RIO CLARO',
  realizados: 0,
  afazer: 0,
  riscos: [],
  exames: [],
  observacoes: 'SEGUIR PCMSO DA CHEMSON',
  preferencial: '',
  atividadesEspeciais: [],
  perfil: '',
  nomeSolicitante: 'THAIS',
  emailSolicitante: 'atendimento@inovacaose.com.br',
  telefoneSolicitante: '(19) 99644-1281',
  anexos: [],
  mensagem: '',
  createdAt: 1725285925106,
  updatedAt: 1725285925106
}



// {
//   id: 'CM000406',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '03/09/2024',
//   horarioAgendamento: '09:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'INOVAÇÃO RH TRABALHOS TEMPORARIOS',
//   codFuncionario: '',
//   funcionario: 'BRUNO AUGUSTO AMORIM',
//   dataNascimento: '30/06/1993',
//   sexo: 'MASCULINO',
//   rg: '488335085',
//   cpf: '41616299827',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '01.969.452/0001-49',
//   unidadeTrabalho: 'CHEMSON',
//   codUnidadeTrabalho: '',
//   setor: 'SOLID CA/ZN',
//   codSetor: '',
//   cargo: 'AJUDANTE DE PRODUÇÃO',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: 'SEGUIR PCMSO DA CHEMSON',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'THAIS',
//   emailSolicitante: 'atendimento@inovacaose.com.br',
//   telefoneSolicitante: '(19) 99644-1281',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725286015936,
//   updatedAt: 1725286015936
// }








// {
//   id: 'CM000409',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '05/09/2024',
//   horarioAgendamento: '13:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'MV SERVIÇOS LTDA',
//   codFuncionario: '',
//   funcionario: 'TALITA APARECIDA CAETANO ALMEIDA',
//   dataNascimento: '18/06/1988',
//   sexo: 'FEMININO',
//   rg: '40247000X',
//   cpf: '32172961841',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '03.384.710/0001-59',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'ESCOLAR',
//   codSetor: '',
//   cargo: 'MONITORA DE ALUNOS',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 3,
//   tipoExame: 'RETORNO AO TRABALHO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: 'CBO 334110\r\nENTREGAR VIA DO ASO AO COLABORADOR',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'LEANDRO OLIVEIRA',
//   emailSolicitante: 'monitoresrioclaro@gmail.com',
//   telefoneSolicitante: '(19) 99887-8604',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725286696648,
//   updatedAt: 1725286696648
// }






// PROBLEMA SAAJ
// {
//   id: 'CM000322',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '11/09/2024',
//   horarioAgendamento: '08:30',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'AED MONITORAMENTO',
//   codFuncionario: '',
//   funcionario: 'HEBE ALVES GONCALVES',
//   dataNascimento: '30/07/1985',
//   sexo: 'FEMININO',
//   rg: '425712539',
//   cpf: '33340387850',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '21.533.191/0001-27',
//   unidadeTrabalho: '',
//   codUnidadeTrabalho: '',
//   setor: 'OPERACIONAL',
//   codSetor: '',
//   cargo: 'SUPERVISORA ADMINISTRATIVA',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 2,
//   tipoExame: 'PERIÓDICO',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'WITHNEY',
//   emailSolicitante: 'withney.caroline@aedmonitoramento.com.br',
//   telefoneSolicitante: '(01) 93315-1030',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725035575936,
//   updatedAt: 1725035575936
// }


// PROBLEMA SAAJ
// {
//   id: 'CM000389',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '03/09/2024',
//   horarioAgendamento: '10:00',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'SARTORICMS',
//   codFuncionario: '',
//   funcionario: 'WILLIAN SANCHES DA SILVA',
//   dataNascimento: '18/07/1984',
//   sexo: 'MASCULINO',
//   rg: '328281529',
//   cpf: '22661939881',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '04.861.623/0001-00',
//   unidadeTrabalho: 'RIO CLARO SP',
//   codUnidadeTrabalho: '',
//   setor: '40204 - CENTRO DE TORNEAMENTO MULTIFUSO',
//   codSetor: '',
//   cargo: 'OPERADOR DE MÁQUINA CNC II C',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'SERGIO LUIS DEBONI',
//   emailSolicitante: 'sergio.deboni@sartori.ind.br',
//   telefoneSolicitante: '(19) 03538-1910',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725282702048,
//   updatedAt: 1725282702048
// }


// ERRO AXIOS
// {
//   id: 'CM000389',
//   chegada: '',
//   dataChegada: '',
//   dataAgendamento: '03/09/2024',
//   horarioAgendamento: '10:00',
//   situacao: 'SOLICITADO',
//   codEmpresa: '',
//   empresa: 'SARTORICMS',
//   codFuncionario: '',
//   funcionario: 'WILLIAN SANCHES DA SILVA',
//   dataNascimento: '18/07/1984',
//   sexo: 'MASCULINO',
//   rg: '328281529',
//   cpf: '22661939881',
//   situacaoFuncionario: 'Ativo',
//   cnpj: '04.861.623/0001-00',
//   unidadeTrabalho: 'RIO CLARO SP',
//   codUnidadeTrabalho: '',
//   setor: '40204 - CENTRO DE TORNEAMENTO MULTIFUSO',
//   codSetor: '',
//   cargo: 'OPERADOR DE MÁQUINA CNC II C',
//   codCargo: '',
//   idFicha: '',
//   dataFicha: '',
//   codTipoExame: 1,
//   tipoExame: 'ADMISSIONAL',
//   unidade: 'RIO CLARO',
//   realizados: 0,
//   afazer: 0,
//   riscos: [],
//   exames: [],
//   observacoes: '',
//   preferencial: '',
//   atividadesEspeciais: [],
//   perfil: '',
//   nomeSolicitante: 'SERGIO LUIS DEBONI',
//   emailSolicitante: 'sergio.deboni@sartori.ind.br',
//   telefoneSolicitante: '(19) 03538-1910',
//   anexos: [],
//   mensagem: '',
//   createdAt: 1725282849898,
//   updatedAt: 1725282849898
// }



 module.exports = MOCK